name: Update cache
description: Install packages and update cache

runs:
  using: 'composite'
  steps:
    - uses: actions/setup-node@v3
      with:
        node-version-file: '.nvmrc'
        cache: 'yarn'

    - name: Packages install
      shell: sh
      run: yarn --frozen-lockfile --prefer-offline

    - name: Build cache script
      shell: sh
      run: yarn build:populate-cache

    - name: Update cache
      shell: sh
      run: yarn cache:update

    - name: Parse cache to separate files
      shell: sh
      run: yarn cache:parse
