name: Update cache
# This action checks if there's new finished proposals every 3h
# If new finished proposal data is found the cache will be warmed up & push
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

on:
  workflow_dispatch:
  schedule:
    - cron: 0 */3 * * *

jobs:
  cache-updates:
    strategy:
      matrix:
        # Only mainnet for now
        network: [mainnet]

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 9
          run_install: false

      - uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Update cache
        run: pnpm run cache:update
        env:
          CORE_NETWORK: ${{ matrix.network }}
          RPC_POLYGON: ${{ secrets.RPC_POLYGON }}
          RPC_OPTIMISM: ${{ secrets.RPC_OPTIMISM }}
          RPC_MAINNET: ${{ secrets.RPC_MAINNET }}
          RPC_BASE: ${{ secrets.RPC_BASE }}
          RPC_ARBITRUM: ${{ secrets.RPC_ARBITRUM }}
          RPC_ZKEVM: ${{ secrets.RPC_ZKEVM }}
          RPC_ZKSYNC: ${{ secrets.RPC_ZKSYNC }}
          IPFS_GATEWAY: ${{ secrets.IPFS_GATEWAY }}

      - name: Parse cache to separate files
        run: pnpm run cache:parse
        env:
          CORE_NETWORK: ${{ matrix.network }}
          RPC_POLYGON: ${{ secrets.RPC_POLYGON }}
          RPC_OPTIMISM: ${{ secrets.RPC_OPTIMISM }}
          RPC_MAINNET: ${{ secrets.RPC_MAINNET }}
          RPC_BASE: ${{ secrets.RPC_BASE }}
          RPC_ARBITRUM: ${{ secrets.RPC_ARBITRUM }}
          RPC_ZKEVM: ${{ secrets.RPC_ZKEVM }}
          RPC_ZKSYNC: ${{ secrets.RPC_ZKSYNC }}
          IPFS_GATEWAY: ${{ secrets.IPFS_GATEWAY }}

      - name: Check code diff and push
        run: |
          if [[ -z $(git status -s) ]]
          then
            echo "tree is clean"
          else
            git config --global user.name 'Cache update'
            git config --global user.email 'cache-bot@bgd.com'
            git pull
            git add .
            git commit -am "chore: automated cache update"
            git push
          exit
          fi
