name: Update cache
# This action checks if there's new finished proposals every 3h
# If new finished proposal data is found the cache will be warmed up & push
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

on:
  workflow_dispatch:
  schedule:
    - cron: 0 */4 * * *

jobs:
  cache-updates:
    strategy:
      matrix:
        # Only mainnet for now
        network: [mainnet]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: 'yarn'

      - name: Packages install
        shell: sh
        run: yarn --frozen-lockfile --prefer-offline

      - name: Update UI cache
        shell: sh
        run: yarn cache:update

      - name: Check code diff and push
        run: |
          if [[ -z $(git status -s) ]]
          then
            echo "tree is clean"
          else
            git config --global user.name 'Cache update'
            git config --global user.email 'cache-bot@bgd.com'
            git pull
            git add .
            git commit -am "chore: automated cache update"
            git push
          exit
          fi
